# Generated by Django 5.1.2 on 2024-10-26 09:39

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comment_answer_delay_mins",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(validators=[core.validators.validate_content_]),
        ),
    ]
